# https://hub.docker.com/r/inanimate/quake3/
# https://github.com/InAnimaTe/docker-quake3
# FROM inanimate/quake3
# https://github.com/LacledesLAN/gamesvr-ioquake3
FROM lacledeslan/gamesvr-ioquake3

COPY baseq3/pak0.pk3 /app/baseq3/pak0.pk3
